escalon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
#from django.views.static import serve

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('administration/', include(('administration.urls','administration'))),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('rooms', views.RoomsView.as_view(), name='rooms'),
    path('hotel', views.HotelView.as_view(), name='hotel'),
    path('contact', views.ContactView.as_view(), name='contact'),
    path('dinner', views.DinnerView.as_view(), name='dinner'),
    path('picnic', views.PicnicView.as_view(), name='picnic'),
    path('wedding', views.WeddingView.as_view(), name='wedding'),
    path('event', views.EventView.as_view(), name='event'),
    path('book_search', views.BookSearchView.as_view(), name='book_search'),
    path('ajax/bookstepone/', views.load_roombook, name='ajax_book_stepone'),
    path('booksteptow/<int:room>/<str:datein>/<str:dateout>/<int:guest>/<int:children>/', views.BookStepTwoView.as_view(), name='book_steptwo'),
    path('book/thanks', views.ThanksView.as_view(), name='thanks'),
    
    path('book_search/<int:room>/', views.BookSearchView.as_view(), name='book_search'),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

escalon/forms.py
# -*- coding: utf-8 -*-
from os.path import basename
from django.utils.translation import ugettext as _
from django import forms
from django.core.exceptions import ValidationError
from escalon.utils import error_messages

from administration.models import Contact, Category, Book, Country


class ContactForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='EMAIL')
    category = forms.ModelChoiceField(queryset=Category.objects.filter(deleted=False).all(), label="Categoría",empty_label='', required=False)
    message = forms.CharField(widget=forms.Textarea, label='MENSAJE')

    class Meta:
        model = Contact
        fields = (
            'first_name',
            'last_name',
            'email',
            'category',
            'message',
        )
        exclude = (
            'phone',
            'date_event',
        )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = error_messages
            self.fields[field].widget.attrs['class'] = ' uk-input uk-text-input-form'

        self.fields['message'].widget.attrs['class'] += ' uk-textarea uk-text-txtarea-form'
        self.fields['category'].widget.attrs['class'] += ' uk-select '


class DinnerPicnicForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='EMAIL')
    date_event = forms.DateField(required=True, label='Fecha del evento')
    message = forms.CharField(widget=forms.Textarea, label='MENSAJE')

    class Meta:
        model = Contact
        fields = (
            'first_name',
            'last_name',
            'phone',
            'email',
            'date_event',
            'message',
        )
        exclude = (
            'category',
            'num_persons',
        )

    def __init__(self, *args, **kwargs):
        super(DinnerPicnicForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = error_messages
            self.fields[field].widget.attrs['class'] = ' uk-input uk-text-input-form'

        self.fields['message'].widget.attrs['class'] += ' uk-textarea uk-text-txtarea-form'
        self.fields['date_event'].widget.attrs['class'] += ' datepicker'


class WeddingEventForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='EMAIL')
    date_event = forms.DateField(required=True, label='Fecha del evento')
    message = forms.CharField(widget=forms.Textarea, label='MENSAJE')
    num_persons = forms.CharField(required=True,  label='Número de personas')

    class Meta:
        model = Contact
        fields = (
            'first_name',
            'last_name',
            'phone',
            'email',
            'date_event',
            'message',
            'num_persons',
        )
        exclude = (
            'category',
        )

    def __init__(self, *args, **kwargs):
        super(WeddingEventForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = error_messages
            self.fields[field].widget.attrs['class'] = ' uk-input uk-text-input-form'

        self.fields['message'].widget.attrs['class'] += ' uk-textarea uk-text-txtarea-form'
        self.fields['date_event'].widget.attrs['class'] += ' datepicker'


class LoginForm(forms.Form):
    username = forms.CharField(label=('Usuario'), max_length=128)
    password = forms.CharField(label=_(u"Contraseña"), widget=forms.PasswordInput, max_length=128)

    def clean_password(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        user = User.objects.filter(Q(username=username)).first()
        if not user:
            raise forms.ValidationError("Este usuario no existe")
        else:
            if not user.check_password(password):
                raise forms.ValidationError("Contraseña incorrecta")
        return password

    
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = error_messages
            self.fields[field].widget.attrs['class'] = 'uk-border-rounded uk-border-2 uk-input uk-form-width-large'


class BookRoomsForm(forms.Form):
    date_in = forms.DateField(required=True, label='Entrada')
    date_out = forms.DateField(required=True, label='Salida')
    guest = forms.IntegerField(required=True, label='Huéspedes')
    children = forms.IntegerField(required=True, label='Niños')

    
    def __init__(self, *args, **kwargs):
        super(BookRoomsForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = error_messages
            self.fields[field].widget.attrs['class'] = 'uk-border-rounded  uk-input uk-input-search'
            self.fields[field].widget.attrs['placeholder'] =  self.fields[field].label
        
        self.fields['date_in'].widget.attrs['class'] += ' datepicker'
        self.fields['date_out'].widget.attrs['class'] += ' datepicker'


class PersonBookForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Correo')
    room = forms.IntegerField(required=True, label='Habitacion')

    class Meta:
        model = Book
        fields = (
            'date_in',
            'date_out',
            'guest',
            'children',
            'first_name',
            'last_name',
            'email',
            'phone',
            'requirements',
            'country',
        )


    def __init__(self, *args, **kwargs):
        super(PersonBookForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = error_messages
            self.fields[field].widget.attrs['class'] = 'uk-border-rounded uk-border-2 uk-input uk-form-width-large uk-input uk-text-input-book'

        self.fields['requirements'].widget.attrs['class'] += ' uk-textarea uk-text-txtarea-book'
        self.fields['country'].widget.attrs['class'] += ' uk-select '

        self.fields['room'].widget = forms.HiddenInput()
        self.fields['date_in'].widget = forms.HiddenInput()
        self.fields['date_out'].widget = forms.HiddenInput()
        self.fields['guest'].widget = forms.HiddenInput()
        self.fields['children'].widget = forms.HiddenInput()

escalon/views.py
from django.views.generic import View, FormView, TemplateView, CreateView
from django.utils.translation import ugettext as _
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

import django.views.generic
from django import forms

from escalon.settings import EMAIL_PREFIX, EMAIL_DOMAIN, DEFAULT_FROM_EMAIL, EMAIL_HOST_USER
from django.core.mail import EmailMultiAlternatives
from django.template import loader

from escalon.forms import ContactForm, LoginForm, BookRoomsForm, PersonBookForm, DinnerPicnicForm, WeddingEventForm
from administration.models import Contact, Category, Room, Book, Country

from datetime import datetime
from decimal import *
from django.contrib.messages import get_messages
#DICT_PROFILE_STATE_TYPE_CHOICES = dict((x, y) for x, y in Book.STATE_TYPE_CHOICES)

def send_mail(request, tipo, type_event):
    category_name = ""

    if (tipo=='contact'):
        email_template_name = 'email_contact.html'
        
        if request.POST['category']:
            category = Category.objects.filter(id=request.POST['category']).values('name').first()
            category_name = category['name']
        
        context = {
            'domain': "%s%s" % (EMAIL_PREFIX, EMAIL_DOMAIN),  # or your domain
            'site_name': 'El Escalón Hotel',
            'protocol': 'http',
            'email':request.POST['email'],
            'first_name':request.POST['first_name'],
            'last_name':request.POST['last_name'],
            'category':category_name,
            'message':request.POST['message'],
        }
    elif(tipo=='dinner' or tipo=='picnic'):
        email_template_name = 'email_events.html'

        context = {
            'domain': "%s%s" % (EMAIL_PREFIX, EMAIL_DOMAIN),  # or your domain
            'site_name': 'El Escalón Hotel',
            'protocol': 'http',
            'email':request.POST['email'],
            'first_name':request.POST['first_name'],
            'last_name':request.POST['last_name'],
            'phone' : request.POST['phone'],
            'date_event' : request.POST['date_event'],
            'message':request.POST['message'],
            'type_event' : type_event,
        }
        subject='El Escalón Hotel - Contáctanos'

    else:
        email_template_name = 'email_events.html'

        context = {
            'domain': "%s%s" % (EMAIL_PREFIX, EMAIL_DOMAIN),  # or your domain
            'site_name': 'El Escalón Hotel',
            'protocol': 'http',
            'email':request.POST['email'],
            'first_name':request.POST['first_name'],
            'last_name':request.POST['last_name'],
            'phone' : request.POST['phone'],
            'date_event' : request.POST['date_event'],
            'num_persons' : request.POST['num_persons'],
            'message':request.POST['message'],
            'type_event' : type_event,
        }
        subject='El Escalón Hotel - '+type_event


    from_email = request.POST['email']
    to_email = [DEFAULT_FROM_EMAIL]

    #from_email = EMAIL_HOST_USER
    #to_email = [request.POST['email'] , 'estefania.heredia@cti.espol.edu.ec']

    html_content = loader.render_to_string(email_template_name, context)
    
    try:
        email_message = EmailMultiAlternatives(subject, html_content, to=to_email, from_email=from_email)   
        email_message.attach_alternative(html_content, "text/html") 
        email_message.mixed_subtype = 'related'

        email_message.send(fail_silently=False)

        return True
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(e)
        return False


def send_mail_book(book, tipo):
    if(tipo=='book'):
        email_template_name = 'email_book.html'
        from_email = DEFAULT_FROM_EMAIL
        to_email = [book.email]
    else:
        email_template_name = 'email_book_admin.html'
        from_email = DEFAULT_FROM_EMAIL
        to_email = [DEFAULT_FROM_EMAIL]

    context = {
        'domain': "%s%s" % (EMAIL_PREFIX, EMAIL_DOMAIN),  # or your domain
        'site_name': 'El Escalón Hotel',
        'protocol': 'http',
        'date_in' : book.date_in,
        'date_out' : book.date_out,
        'guest' : book.guest,
        'children' : book.children ,
        'first_name' : book.first_name ,
        'last_name' : book.last_name,
        'email' : book.email,
        'phone' :  book.phone,
        'country' : book.country.name,
        'requirements' : book.requirements,
        'room_name' : book.room.name,
        'subtotal' :  round(book.subtotal,2), 
        'tax' : round(book.tax,2),
        'total' : round(book.total,2),
    }

    #from_email = DEFAULT_FROM_EMAIL
    #to_email = [book.email , 'estefania.heredia@cti.espol.edu.ec']
    
    #from_email = EMAIL_HOST_USER
    #to_email = [request.POST['email'] , 'estefania.heredia@cti.espol.edu.ec']

    html_content = loader.render_to_string(email_template_name, context)
    subject='El Escalón Hotel - Reservación'

    try:
        email_message = EmailMultiAlternatives(subject, html_content, to=to_email, from_email=from_email)   
        email_message.attach_alternative(html_content, "text/html") 
        email_message.mixed_subtype = 'related'

        email_message.send(fail_silently=False)

        return True
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(e)
        return False


class HomeView(TemplateView):
    """docstring for HomeView"""
    template_name = "index.html"

    
    def form_valid(self, form):
        return super(HomeView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        data = {
            'title': _(u'Home'),
            }
        return render(request, self.template_name, data)


class RoomsView(django.views.generic.ListView):
    """docstring for RoomsView"""
    model = Room
    template_name = "rooms.html"

    def get_queryset(self):
        return super(RoomsView, self).get_queryset().filter(deleted=False).order_by('id')

    def get_context_data(self, **kwargs):
        context = super(RoomsView, self).get_context_data(**kwargs)
        context['title'] = _(u"Habitaciones")
        return context


class HotelView(TemplateView):
    """docstring for HotelView"""
    template_name = "hotel.html"

    
    def form_valid(self, form):
        return super(HotelView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        data = {
            'title': _(u'El Hotel'),
            }
        return render(request, self.template_name, data)


class ContactView(CreateView):
    """docstring for ContactView"""
    model = Contact
    template_name = "contact.html"

    def send_mail(self, tipo, type_event): send_mail(tipo, type_event)


    def get(self, request, *args, **kwargs):
        data = {
            'title': _(u'Contáctanos'),
            'form': ContactForm(),
            }
        return render(request, self.template_name, data)

    def post(self, request, *arg, **kwargs):
        try:
            category = Category.objects.filter(id=request.POST.get('category')).first()

            contact = Contact()
            contact.first_name = request.POST.get('first_name')
            contact.last_name = request.POST.get('last_name')
            contact.email = request.POST.get('email')
            contact.message = request.POST.get('message')
            contact.category = category
            contact.save()

            if send_mail(request, 'contact', ''):
                messages.success(request, _(u'Se ha enviado correctamente su solicitud.'))
                return redirect("index")
            else:
                messages.error(request, _(u'Existe un error al enviar su solicitud.'))
                return self.get(request)
            
        except Exception as e:
            import traceback;
            traceback.print_exc()
            print(e)
            messages.error(request, _(u'Existe un problema al guardar su información.'))
            return self.get(request)


class DinnerView(CreateView):
    """docstring for DinnerView"""
    model = Contact
    template_name = "dinnerpicnic.html"


    def send_mail(self, tipo, type_event): send_mail(tipo, type_event)


    def get(self, request, *args, **kwargs):
        data = {
            'title': _(u'Cenas románticas'),
            'form': DinnerPicnicForm(),
            }
        return render(request, self.template_name, data)

    def post(self, request, *arg, **kwargs):
        try:
            category = Category.objects.filter(id=1).first()

            contact = Contact()
            contact.first_name = request.POST.get('first_name')
            contact.last_name = request.POST.get('last_name')
            contact.email = request.POST.get('email')
            contact.phone = request.POST.get('phone')
            contact.date_event = request.POST.get('date_event')
            contact.message = request.POST.get('message')
            contact.category = category
            contact.save()

            if send_mail(request, 'dinner', category.name):
                messages.success(request, _(u'Se ha enviado correctamente su solicitud.'))
                return redirect("index")
            else:
                messages.error(request, _(u'Existe un error al enviar su solicitud.'))
                return self.get(request)
            
        except Exception as e:
            import traceback;
            traceback.print_exc()
            print(e)
            messages.error(request, _(u'Existe un problema al guardar su información.'))
            return self.get(request)
            

class PicnicView(CreateView):
    """docstring for ContactView"""
    model = Contact
    template_name = "dinnerpicnic.html"

escalon/templates/book_search.html
{% extends "base.html" %}
{% load static %}


{% block container %}
<div class="uk-card" style="background: #3895d8;">
    <div class="uk-padding">
        {% include "step1_book.html" with submit_value="Buscar" attr="" form_classes="uk-grid-small" show_help_texts_in_hidden="True" %}
    </div>
</div>

<div id="uk-seccion-list-rooms" class="uk-section uk-section-default uk-section-small">
    <div class="uk-container ">
        {% if object_list %}
        <div class="uk-child-width-1-2@s uk-child-width-1-3@m" uk-grid uk-height-match="target: > div > .uk-card">
            {% for object in object_list %}
            
                <div class="uk-card uk-card-hover">

                	<div class="uk-card-header">
                		<div class="uk-text-center">
                            <div class="uk-card-media-top" >
                            	{% if object.attach_files.all %}
                                 {% with object.attach_files.all|first as act %}
                                    {% if act %}
                                      <img src=" {{  act.get_attach_file_src.url }}" >
                                    {% endif %}
                                  {% endwith %}

                                {% endif %}
                            </div>
                        </div>
                    </div> 
                     

                      

                	<div class="uk-card-body uk-padding-remove-top uk-padding-remove-bottom ">

                        <h4 class="uk-text-bold uk-text-uppercase uk-text-title1 uk-margin-small-bottom">{{object.name}}</h4>
                        
                        <div class="uk-margin-small-bottom">
	                        <ul class="uk-iconnav">
	                        {%if object.service_types.all%}
                                {% for service in object.service_types.all %}
                                    {% if service.id == 1 %}
                                    <li><span class="uk-icon uk-icon-image uk-icon-services" style="background-image: url({% static 'img/services/habitaciones_icono_aireacon.png' %});"></span></li>
                                    {% endif %}
                                    {% if service.id == 2 %}
                                    <li><span class="uk-icon uk-icon-image uk-icon-services" style="background-image: url({% static 'img/services/habitaciones_icono_wifi.png' %});"></span></li>
                                    {% endif %}
                                    {% if service.id == 3 %}
                                    <li><span class="uk-icon uk-icon-image uk-icon-services" style="background-image: url({% static 'img/services/habitaciones_icono_tv.png' %});"></span></li>
                                    {% endif %}
                                    {% if service.id == 9 %}
                                    <li><span class="uk-icon uk-icon-image uk-icon-services" style="background-image: url({% static 'img/services/habitaciones_icono_bano.png' %});"></span></li>
                                    {% endif %}
                                    {% if service.id == 5 %}
                                    <li><span class="uk-icon uk-icon-image uk-icon-services" style="background-image: url({% static 'img/services/habitaciones_icono_toallas.png' %});"></span></li>
                                    {% endif %}
                                {%endfor%}
                            {% else %}    
	                                <li><p class="uk-descripcion-room uk-margin-small-top">No existe información para mostrar</p><li>
	                        {% endif %}
	                        </ul>
	                    </div>

	                    
                    </div>

                    <div class="uk-card-footer uk-padding-remove-top">
                    	<a class="" href="#modal-{{object.id}}" uk-toggle>Más información ❯</a>
                    	

                        <div class="uk-text-roomprice uk-text-uppercase"> <b>${{object.week_price}}</b> por noche</div>

		                <a id="id_book_{{object.id}}" class="uk-button uk-button-default uk-button-reservar" onclick="bookstepone({{object.id}})">Reservar</a>


                   	</div>

                	<div id="modal-{{object.id}}" class="uk-flex-top" uk-modal>
                            <div class="uk-modal-dialog uk-margin-auto-vertical">

                                <button class="uk-modal-close-default" type="button" uk-close></button>

                                <div class="uk-modal-header">
                                    <h3 class="uk-modal-title">{{object.name}}</h3>
                                </div>

                            </div>
                    </div>

                </div>

               
        {% endfor %}
        </div>
        {% else %}
            <p>No existe información para mostrar.</p>
        {% endif %}
    </div>
</div>

<script type="text/javascript">
	function bookstepone(r){
        if( $("#id_date_in").val().length > 0 && $("#id_date_out").val().length > 0) {
    		$.ajax({
                url: "{% url 'ajax_book_stepone' %}",
                data: {
                'r': r,
                'di':$("#id_date_in").val(),
                'do':$("#id_date_out").val(),
                'g': $("#id_guest").val().length == 0 ?  1 : $("#id_guest").val(),
                'c': $("#id_children").val().length == 0 ?  0 : $("#id_children").val()
                },
                success: function (data) {
                	$("#uk-seccion-list-rooms").hide();
                    $("#uk_seccion_book_room").html(data);
                }
            });
        }else{
            if( $("#id_date_in").val().length == 0 ) 
                UIkit.notification({message: 'Debe escoger una fecha de entrada para reservar.', status: 'danger'});
            else if( $("#id_date_out").val().length == 0 ) 
                UIkit.notification({message: 'Debe escoger una fecha de salida para reservar.', status: 'danger'});
            else  
                UIkit.notification({message: 'Exite un problema.', status: 'danger'});

        }      
	}

</script>


<div id="uk_seccion_book_room"  class="uk-section uk-section-default uk-section-small" style="background: #edeeef;">
</div>



{% endblock %}

escalon/templates/dinnerpicnic.html
{% extends "base.html" %}
{% load static %}


{% block container %}

<div class="uk-card uk-child-width-1-2@s uk-margin-remove" style="background: #0c3c7d;" uk-grid >
        <div class="uk-flex-last@s uk-card-media-right uk-cover-container uk-padding-remove">
            <div class="map-responsive">
                <img data-src="{% static 'img/home_reserva1_cena.png' %}" width="1800" height="1200" alt="" uk-img>

             </div>
        </div>

        <div class="uk-padding-left uk-padding-right uk-padding-remove-top uk-first-column">
            
                {% include "eventform.html" with submit_value="Enviar" attr="" form_classes="uk-form-stacked" show_help_texts_in_hidden="True" %}
            
        </div>
    </div>
    
    
{% endblock %}

escalon/templates/email_book.html
{% load static %}
{% load staticfiles %}
{% load i18n %}
{% autoescape off %}
<!DOCTYPE html>
<html xmlns:v="urn:schemas-microsoft-com:vml">
<body>
<table border="0" bgcolor="#fafafa" cellspacing="0" cellpadding="0" style="background: #fafafa; border-collapse: collapse; font-family: Arial,sans-serif; font-weight: normal; margin: 0; padding: 0; width: 100%" width="100%" height="100%">
    <tr>
        <td>
            <table style="border-collapse:collapse;font-family:Arial,sans-serif;font-weight:normal;margin:0 auto;max-width:600px;min-width:600px;width:600px" width="600" cellspacing="0" cellpadding="0" border="0" align="center">
                <tr>
                    <td>
                        <div style="padding:30px;background: #ffffff;border-collapse: collapse;border: 2px solid #13274b;color: #13274b;font-family:Roboto,arial;font-size:14px;line-height:24px;font-weight: normal;width: 598px;border-radius: 0;">

                            <h3 style="text-align: center;">EL ESCALÓN HOTEL</h3>
    
                            <div style="height: 3px;background: #476C7B;margin-top:15px;margin-bottom:15px;margin-bottom:10px;"></div>

                            <table>
                                <tbody>
                                    <tr>
                                        <td style="width:140px"><img src="{% static 'img/logo.png' %}" height="90px"></td>
                                        <td>
                                            <p>{% trans "Dear" %} {{first_name}} </p>

                                            <p><strong>Your reservation is confirmed!</strong></p>

                                            <p>
                                                {% blocktrans %}We receive your reservation of the <strong>{{room_name}}</strong>.  
                                                {% endblocktrans %}
                                            </p>
                                            
                                            <p> {% blocktrans %}Date of admission: {{date_in}} {% endblocktrans %}</p>
                                            <p> {% blocktrans %}Date of departure: {{date_out}} {% endblocktrans %}</p>
                                            

                                            
                                            <p>{% blocktrans %}If you have any questions email us to: <strong>reservas@escalonhotel.com
                                            </strong>.{% endblocktrans %}</p>
                                            
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                            <div style="height: 3px;background: #476C7B;margin-top:15px;margin-bottom:15px;margin-bottom:10px"></div>
                            <p>{% blocktrans %}Sincerely,{% endblocktrans %}</p>
                            <p> Webmaster</p>
                            <p><b>{% blocktrans %}{{ site_name }}{% endblocktrans %}</b></p>
                        </div>

                        <div style="background: #D8D8D8;font-size: 14px;">
                            <div style="color: #13274b;padding: 5px;margin: 15px;text-align: center;background-color: rgba(256,256,256,0.5);">
                                <p>
                                    <br>
                                    <a href="{{ domain }}" style="color: #000668; text-decoration: none;">{{ domain }}</a>
                                </p>
                            </div>

                        </div>
                    </td>
                </tr>
                <tr><td style="height:60px"></td></tr>

            </table>
        </td>
    </tr>
</table>
</body>
</html>
{% endautoescape %}

escalon/templates/paginator.html
    <ul class="uk-pagination uk-flex-center">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">❮</a></li>
    {% else %}
      <li class="uk-disabled"><span>❮</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="uk-active"><span>{{ i }} <span class="sr-only"></span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">❯</a></li>
    {% else %}
      <li class="uk-disabled"><span❯</span></li>
    {% endif %}
  </ul>

escalon/templates/thanks.html
{% extends "base.html" %}
{% load static %}

{% block container %}


	<div class="uk-inline uk-dark">
            <img src="{% static 'img/bannerhome1.png' %}" alt="" width="1800" height="1200">
            <div class="uk-overlay-default uk-position-cover uk-overlay-thanks">
                <div class="uk-position-center">
                    <h3 class="uk-text-bold uk-text-title2  uk-text-center uk-text-uppercase " style="font-size: 30px">Tu reserva ha sido</h3>

 					<h3 class="uk-text-bold uk-text-title2 uk-text-uppercase  uk-text-center uk-margin-small-top uk-margin-small-bottom" style="font-size: 30px">realizada.</h3>

 					<h3 class="uk-text-bold uk-text-title2 uk-text-uppercase  uk-text-center uk-margin-large-top" style="font-size: 30px">Te esperamos</h3>

                </div>
            </div>
        </div>
    	
		   

       
			

            
	
	


{% endblock %}

escalon/templates/weddingevent.html
{% extends "base.html" %}
{% load static %}


{% block container %}

<div class="uk-card uk-child-width-1-2@s uk-margin-remove" style="background: #0c3c7d;" uk-grid >
        <div class="uk-flex-last@s uk-card-media-right uk-cover-container uk-padding-remove">
            <div class="map-responsive">
                <img data-src="{% static 'img/home_reserva1_cena.png' %}" width="1800" height="1200" alt="" uk-img>

             </div>
        </div>

        <div class="uk-padding-left uk-padding-right uk-padding-remove-top uk-first-column">
            
                {% include "eventform2.html" with submit_value="Enviar" attr="" form_classes="uk-form-stacked" show_help_texts_in_hidden="True" %}
            
        </div>
    </div>
    
    
{% endblock %}